INSERT INTO DBO.MS_Country
VALUES ('GER','GERMAN')
INSERT INTO DBO.MS_Country
VALUES ('IND','INDIA')
INSERT INTO DBO.MS_Country
VALUES ('JAP','JAPAN')
INSERT INTO DBO.MS_Country
VALUES ('PAK','PAKISTAN')
INSERT INTO DBO.MS_Country
VALUES ('SL','SRILANKA')
INSERT INTO DBO.MS_Country
VALUES ('USA','UNITED STATES OF AMERICA')