INSERT INTO MS_LibraryType(TypeName,IsActive) 
VALUES ('Message',1)
INSERT INTO MS_LibraryType(TypeName,IsActive) 
VALUES ('FILE',1)
INSERT INTO MS_LibraryType(TypeName,IsActive) 
VALUES ('GRAPHIC',1)
INSERT INTO MS_LibraryType(TypeName,IsActive) 
VALUES ('QUESTION',1)
INSERT INTO MS_LibraryType(TypeName,IsActive) 
VALUES ('SURVEY',1)
