INSERT INTO MS_MessageType(MessageTypeName)
VALUES ('END OF SURVEY')
INSERT INTO MS_MessageType(MessageTypeName)
VALUES ('GENERAL')
INSERT INTO MS_MessageType(MessageTypeName)
VALUES ('INACTIVE SURVEY')
INSERT INTO MS_MessageType(MessageTypeName)
VALUES ('INVITE')
INSERT INTO MS_MessageType(MessageTypeName)
VALUES ('REMINDER')
INSERT INTO MS_MessageType(MessageTypeName)
VALUES ('THANK YOU')