INSERT INTO MS_Respondent(RespondentName,CustomerId)
VALUES ('SANDEEP',1)
INSERT INTO MS_Respondent(RespondentName,CustomerId)
VALUES ('JHONNY',1)
INSERT INTO MS_Respondent(RespondentName,CustomerId)
VALUES ('KISHORE',1)
INSERT INTO MS_Respondent(RespondentName,CustomerId)
VALUES ('NILESH',1)
INSERT INTO MS_Respondent(RespondentName,CustomerId)
VALUES ('PARESH',1)
INSERT INTO MS_Respondent(RespondentName,CustomerId)
VALUES ('RAJESH',1)
INSERT INTO MS_Respondent(RespondentName,CustomerId)
VALUES ('SARIKA',1)
INSERT INTO MS_Respondent(RespondentName,CustomerId)
VALUES ('UNNI',1)
INSERT INTO MS_Respondent(RespondentName,CustomerId)
VALUES ('VINAY',1)
INSERT INTO MS_Respondent(RespondentName,CustomerId)
VALUES ('VISHAL',1)