INSERT INTO DBO.MS_State
VALUES ('CAL','CALIFORNIA',6)
INSERT INTO DBO.MS_State
VALUES ('COL','COLOMBO',5)
INSERT INTO DBO.MS_State
VALUES ('GUJ','GUJRAT',2)
INSERT INTO DBO.MS_State
VALUES ('MAH','MAHARASHTRA',2)
INSERT INTO DBO.MS_State
VALUES ('NY','NEW YORK',6)