INSERT INTO MS_SurveyStatus(StatusId,SurveyStatusName)
VALUES(0,'Inactive')
INSERT INTO MS_SurveyStatus(StatusId,SurveyStatusName)
VALUES(1,'Active')
INSERT INTO MS_SurveyStatus(StatusId,SurveyStatusName)
VALUES(2,'Completed')