INSERT INTO MS_SurveySettings(RespondentName,CustomerId)
VALUES ('UI','BTN_BACK','BACK BUTTON')
INSERT INTO MS_SurveySettings(RespondentName,CustomerId)
VALUES ('UI','BTN_SAVECONTIUNE','SAVE AND CONTINUE LATER')
INSERT INTO MS_SurveySettings(RespondentName,CustomerId)
VALUES ('EOS','CB_DEFAULTEOS','Default End of Survey')
INSERT INTO MS_SurveySettings(RespondentName,CustomerId)
VALUES ('SEC','CB_OPENACCESS','OPEN ACCESS')