TRUNCATE TABLE DBO.MS_TimeZone

GO
INSERT INTO MS_TimeZone VALUES('GMT+04:30','Kabul')
INSERT INTO MS_TimeZone VALUES('GMT-09:00','Alaska')
INSERT INTO MS_TimeZone VALUES('GMT+03:00','Kuwait, Riyadh')
INSERT INTO MS_TimeZone VALUES('GMT+04:00','Abu Dhabi, Muscat')
INSERT INTO MS_TimeZone VALUES('GMT+03:00','Baghdad')
INSERT INTO MS_TimeZone VALUES('GMT-04:00','Atlantic Time (Canada)')
INSERT INTO MS_TimeZone VALUES('GMT+09:30','Darwin')
INSERT INTO MS_TimeZone VALUES('GMT+10:00','Canberra, Melbourne, Sydney')
INSERT INTO MS_TimeZone VALUES('GMT+04:00','Baku')
INSERT INTO MS_TimeZone VALUES('GMT-01:00','Azores')
INSERT INTO MS_TimeZone VALUES('GMT-06:00','Saskatchewan')
INSERT INTO MS_TimeZone VALUES('GMT-01:00','Cape Verde Islands')
INSERT INTO MS_TimeZone VALUES('GMT+04:00','Yerevan')
INSERT INTO MS_TimeZone VALUES('GMT+09:30','Adelaide')
INSERT INTO MS_TimeZone VALUES('GMT-06:00','Central America')
INSERT INTO MS_TimeZone VALUES('GMT+06:00','Astana, Dhaka')
INSERT INTO MS_TimeZone VALUES('GMT-04:00','Manaus')
INSERT INTO MS_TimeZone VALUES('GMT+01:00','Belgrade, Bratislava, Budapest, Ljubljana, Prague')
INSERT INTO MS_TimeZone VALUES('GMT+01:00','Sarajevo, Skopje, Warsaw, Zagreb')
INSERT INTO MS_TimeZone VALUES('GMT+11:00','Magadan, Solomon Islands, New Caledonia')
INSERT INTO MS_TimeZone VALUES('GMT-06:00','Central Time (US and Canada)')
INSERT INTO MS_TimeZone VALUES('GMT-06:00','Guadalajara, Mexico City, Monterrey')
INSERT INTO MS_TimeZone VALUES('GMT+08:00','Beijing, Chongqing, Hong Kong SAR, Urumqi')
INSERT INTO MS_TimeZone VALUES('GMT-12:00','International Date Line West')
INSERT INTO MS_TimeZone VALUES('GMT+03:00','Nairobi')
INSERT INTO MS_TimeZone VALUES('GMT+10:00','Brisbane')
INSERT INTO MS_TimeZone VALUES('GMT+02:00','Minsk')
INSERT INTO MS_TimeZone VALUES('GMT-03:00','Brasilia')
INSERT INTO MS_TimeZone VALUES('GMT-05:00','Eastern Time (US and Canada)')
INSERT INTO MS_TimeZone VALUES('GMT+02:00','Cairo')
INSERT INTO MS_TimeZone VALUES('GMT+05:00','Ekaterinburg')
INSERT INTO MS_TimeZone VALUES('GMT+12:00','Fiji Islands, Kamchatka, Marshall Islands')
INSERT INTO MS_TimeZone VALUES('GMT+02:00','Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius')
INSERT INTO MS_TimeZone VALUES('GMT+04:00','Tblisi')
INSERT INTO MS_TimeZone VALUES('GMT','Greenwich Mean Time : Dublin, Edinburgh, Lisbon,')
INSERT INTO MS_TimeZone VALUES('GMT-03:00','Greenland')
INSERT INTO MS_TimeZone VALUES('GMT','Casablanca, Monrovia')
INSERT INTO MS_TimeZone VALUES('GMT+02:00','Athens, Bucharest, Istanbul')
INSERT INTO MS_TimeZone VALUES('GMT-10:00','Hawaii')
INSERT INTO MS_TimeZone VALUES('GMT+05:30','Chennai, Kolkata, Mumbai, New Delhi')
INSERT INTO MS_TimeZone VALUES('GMT+03:30','Tehran')
INSERT INTO MS_TimeZone VALUES('GMT+02:00','Jerusalem')
INSERT INTO MS_TimeZone VALUES('GMT+09:00','Seoul')
INSERT INTO MS_TimeZone VALUES('GMT-02:00','Mid-Atlantic')
INSERT INTO MS_TimeZone VALUES('GMT-07:00','Mountain Time (US and Canada)')
INSERT INTO MS_TimeZone VALUES('GMT-07:00','Chihuahua, La Paz, Mazatlan')
INSERT INTO MS_TimeZone VALUES('GMT+06:30','Yangon (Rangoon)')
INSERT INTO MS_TimeZone VALUES('GMT+06:00','Almaty, Novosibirsk')
INSERT INTO MS_TimeZone VALUES('GMT+02:00','Windhoek')
INSERT INTO MS_TimeZone VALUES('GMT+05:45','Kathmandu')
INSERT INTO MS_TimeZone VALUES('GMT+12:00','Auckland, Wellington')
INSERT INTO MS_TimeZone VALUES('GMT-03:30','Newfoundland and Labrador')
INSERT INTO MS_TimeZone VALUES('GMT+08:00','Irkutsk, Ulaanbaatar')
INSERT INTO MS_TimeZone VALUES('GMT+07:00','Krasnoyarsk')
INSERT INTO MS_TimeZone VALUES('GMT-04:00','Santiago')
INSERT INTO MS_TimeZone VALUES('GMT-08:00','Pacific Time (US and Canada); Tijuana')
INSERT INTO MS_TimeZone VALUES('GMT+01:00','Brussels, Copenhagen, Madrid, Paris')
INSERT INTO MS_TimeZone VALUES('GMT+03:00','Moscow, St.Petersburg, Volgograd')
INSERT INTO MS_TimeZone VALUES('GMT-03:00','Buenos Aires, Georgetown')
INSERT INTO MS_TimeZone VALUES('GMT-05:00','Bogota, Lima, Quito')
INSERT INTO MS_TimeZone VALUES('GMT-04:00','Caracas, La Paz')
INSERT INTO MS_TimeZone VALUES('GMT-11:00','Midway Island, Samoa')
INSERT INTO MS_TimeZone VALUES('GMT+07:00','Bangkok, Hanoi, Jakarta')
INSERT INTO MS_TimeZone VALUES('GMT+08:00','Kuala Lumpur, Singapore')
INSERT INTO MS_TimeZone VALUES('GMT+02:00','Harare, Pretoria')
INSERT INTO MS_TimeZone VALUES('GMT+06:00','Sri Jayawardenepura')
INSERT INTO MS_TimeZone VALUES('GMT+08:00','Taipei')
INSERT INTO MS_TimeZone VALUES('GMT+10:00','Hobart')
INSERT INTO MS_TimeZone VALUES('GMT+09:00','Osaka, Sapporo, Tokyo')
INSERT INTO MS_TimeZone VALUES('GMT+13:00','Nuku''alofa')
INSERT INTO MS_TimeZone VALUES('GMT-05:00','Indiana (East)')
INSERT INTO MS_TimeZone VALUES('GMT-07:00','Arizona')
INSERT INTO MS_TimeZone VALUES('GMT+10:00','Vladivostok')
INSERT INTO MS_TimeZone VALUES('GMT+08:00','Perth')
INSERT INTO MS_TimeZone VALUES('GMT+01:00','West Central Africa')
INSERT INTO MS_TimeZone VALUES('GMT+01:00','Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna')
INSERT INTO MS_TimeZone VALUES('GMT+05:00','Islamabad, Karachi, Tashkent')
INSERT INTO MS_TimeZone VALUES('GMT+10:00','Guam, PortMoresby')
INSERT INTO MS_TimeZone VALUES('GMT+09:00','Yakutsk')
