CREATE TABLE DBO.TempCountry
(CountryId INT,CountryName VARCHAR(150),CountryCode VARCHAR(20))

insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(1,'Afghanistan','AF')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(2,'Albania','AL')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(3,'Algeria','AG')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(4,'American Samoa','AQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(5,'Andorra','AN')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(6,'Angola','AO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(7,'Anguilla','AV')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(8,'Antarctica','AY')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(9,'Antigua and Barbuda','AC')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(10,'Argentina','AR')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(11,'Armenia','AM')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(12,'Aruba','AA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(13,'Ashmore and Cartier','AT')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(14,'Australia','AS')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(15,'Austria','AU')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(16,'Azerbaijan','AJ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(18,'Bahrain','BA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(19,'Baker Island','FQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(20,'Bangladesh','BG')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(21,'Barbados','BB')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(22,'Bassas da India','BS')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(23,'Belarus','BO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(24,'Belgium','BE')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(25,'Belize','BH')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(26,'Benin','BN')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(27,'Bermuda','BD')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(28,'Bhutan','BT')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(29,'Bolivia','BL')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(30,'Bosnia and Herzegovina','BK')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(31,'Botswana','BC')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(32,'Bouvet Island','BV')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(33,'Brazil','BR')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(34,'British Indian Ocean Territory','IO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(35,'British Virgin Islands','VI')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(36,'Brunei Darussalam','BX')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(37,'Bulgaria','BU')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(38,'Burkina Faso','UV')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(39,'Burma','BM')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(40,'Burundi','BY')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(41,'Cambodia','CB')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(42,'Cameroon','CM')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(43,'Canada','CA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(44,'Cape Verde','CV')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(45,'Cayman Islands','CJ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(46,'Central African Republic','CT')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(47,'Chad','CD')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(48,'Chile','CI')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(49,'China','CH')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(50,'Christmas Island','KT')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(51,'Clipperton Island','IP')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(52,'Cocos (Keeling) Islands','CK')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(53,'Colombia','CO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(54,'Comoros','CN')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(55,'Congo, Democratic Republic of the','CG')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(56,'Congo, Republic of the','CF')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(57,'Cook Islands','CW')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(58,'Coral Sea Islands','CR')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(59,'Costa Rica','CS')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(60,'Cote d''Ivoire','IV')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(61,'Croatia','HR')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(62,'Cuba','CU')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(63,'Cyprus','CY')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(64,'Czech Republic','EZ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(65,'Denmark','DA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(66,'Djibouti','DJ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(67,'Dominica','DO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(68,'Dominican Republic','DR')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(69,'East Timor','TT')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(70,'Ecuador','EC')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(71,'Egypt','EG')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(72,'El Salvador','ES')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(73,'Equatorial Guinea','EK')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(74,'Eritrea','ER')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(75,'Estonia','EN')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(76,'Ethiopia','ET')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(77,'Europa Island','EU')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(78,'Falkland Islands (Islas Malvinas)','FK')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(79,'Faroe Islands','FO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(80,'Fiji','FJ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(81,'Finland','FI')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(82,'France','FR')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(83,'France, Metropolitan','--')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(84,'French Guiana','FG')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(85,'French Polynesia','FP')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(86,'French Southern and Antarctic Lands','FS')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(87,'Gabon','GB')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(89,'Gaza Strip','GZ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(90,'Georgia','GG')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(91,'Germany','GM')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(92,'Ghana','GH')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(93,'Gibraltar','GI')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(94,'Glorioso Islands','GO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(95,'Greece','GR')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(96,'Greenland','GL')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(97,'Grenada','GJ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(98,'Guadeloupe','GP')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(99,'Guam','GQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(100,'Guatemala','GT')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(101,'Guernsey','GK')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(102,'Guinea','GV')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(103,'Guinea-Bissau','PU')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(104,'Guyana','GY')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(105,'Haiti','HA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(106,'Heard Island and McDonald Islands','HM')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(107,'Holy See (Vatican City)','VT')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(108,'Honduras','HO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(109,'Hong Kong (SAR)','HK')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(110,'Howland Island','HQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(111,'Hungary','HU')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(112,'Iceland','IC')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(113,'India','IN')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(114,'Indonesia','ID')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(115,'Iran','IR')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(116,'Iraq','IZ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(117,'Ireland','EI')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(118,'Israel','IS')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(119,'Italy','IT')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(120,'Jamaica','JM')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(121,'Jan Mayen','JN')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(122,'Japan','JA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(123,'Jarvis Island','DQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(124,'Jersey','JE')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(125,'Johnston Atoll','JQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(126,'Jordan','JO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(127,'Juan de Nova Island','JU')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(128,'Kazakhstan','KZ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(129,'Kenya','KE')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(130,'Kingman Reef','KQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(131,'Kiribati','KR')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(132,'Korea, North','KN')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(133,'Korea, South','KS')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(134,'Kuwait','KU')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(135,'Kyrgyzstan','KG')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(136,'Laos','LA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(137,'Latvia','LG')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(138,'Lebanon','LE')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(139,'Lesotho','LT')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(140,'Liberia','LI')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(141,'Libya','LY')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(142,'Liechtenstein','LS')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(143,'Lithuania','LH')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(144,'Luxembourg','LU')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(145,'Macao','MC')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(146,'Macedonia, The Former Yugoslav Republic of','MK')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(147,'Madagascar','MA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(148,'Malawi','MI')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(149,'Malaysia','MY')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(150,'Maldives','MV')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(151,'Mali','ML')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(152,'Malta','MT')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(153,'Man, Isle of','IM')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(154,'Marshall Islands','RM')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(155,'Martinique','MB')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(156,'Mauritania','MR')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(157,'Mauritius','MP')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(158,'Mayotte','MF')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(159,'Mexico','MX')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(160,'Micronesia, Federated States of','FM')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(161,'Midway Islands','MQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(162,'Miscellaneous (French)','--')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(163,'Moldova','MD')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(164,'Monaco','MN')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(165,'Mongolia','MG')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(166,'Montenegro','--')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(167,'Montserrat','MH')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(168,'Morocco','MO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(169,'Mozambique','MZ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(170,'Myanmar','--')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(171,'Namibia','WA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(172,'Nauru','NR')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(173,'Navassa Island','BQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(174,'Nepal','NP')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(175,'Netherlands','NL')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(176,'Netherlands Antilles','NT')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(177,'New Caledonia','NC')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(178,'New Zealand','NZ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(179,'Nicaragua','NU')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(180,'Niger','NG')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(181,'Nigeria','NI')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(182,'Niue','NE')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(183,'Norfolk Island','NF')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(184,'Northern Mariana Islands','CQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(185,'Norway','NO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(186,'Oman','MU')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(187,'Pakistan','PK')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(188,'Palau','PS')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(275,'Palestinian Territory, Occupied','--')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(189,'Palmyra Atoll','LQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(190,'Panama','PM')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(191,'Papua New Guinea','PP')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(192,'Paracel Islands','PF')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(193,'Paraguay','PA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(194,'Peru','PE')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(195,'Philippines','RP')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(196,'Pitcairn Islands','PC')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(197,'Poland','PL')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(198,'Portugal','PO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(199,'Puerto Rico','RQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(200,'Qatar','QA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(201,'Reunion','RE')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(202,'Romania','RO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(203,'Russia','RS')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(204,'Rwanda','RW')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(205,'Saint Helena','SH')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(206,'Saint Kitts and Nevis','SC')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(207,'Saint Lucia','ST')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(208,'Saint Pierre and Miquelon','SB')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(209,'Saint Vincent and the Grenadines','VC')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(210,'Samoa','WS')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(211,'San Marino','SM')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(212,'Sao Tome and Proncipe','TP')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(213,'Saudi Arabia','SA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(214,'Senegal','SG')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(215,'Serbia','--')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(216,'Serbia and Montenegro','--')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(217,'Seychelles','SE')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(218,'Sierra Leone','SL')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(219,'Singapore','SN')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(220,'Slovakia','LO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(221,'Slovenia','SI')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(222,'Solomon Islands','BP')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(223,'Somalia','SO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(224,'South Africa','SF')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(225,'South Georgia and the South Sandwich Islands','SX')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(226,'Spain','SP')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(227,'Spratly Islands','PG')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(228,'Sri Lanka','CE')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(229,'Sudan','SU')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(230,'Suriname','NS')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(231,'Svalbard','SV')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(232,'Swaziland','WZ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(233,'Sweden','SW')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(234,'Switzerland','SZ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(235,'Syria','SY')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(236,'Taiwan','TW')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(237,'Tajikistan','TI')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(238,'Tanzania','TZ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(239,'Thailand','TH')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(17,'The Bahamas','BF')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(88,'The Gambia','GA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(240,'Togo','TO')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(241,'Tokelau','TL')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(242,'Tonga','TN')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(243,'Trinidad and Tobago','TD')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(244,'Tromelin Island','TE')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(245,'Tunisia','TS')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(246,'Turkey','TU')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(247,'Turkmenistan','TX')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(248,'Turks and Caicos Islands','TK')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(249,'Tuvalu','TV')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(250,'Uganda','UG')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(251,'Ukraine','UP')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(252,'United Arab Emirates','AE')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(253,'United Kingdom','UK')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(254,'United States','US')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(255,'United States Minor Outlying Islands','--')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(256,'Uruguay','UY')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(257,'Uzbekistan','UZ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(258,'Vanuatu','NH')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(259,'Venezuela','VE')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(260,'Vietnam','VM')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(261,'Virgin Islands','VQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(262,'Virgin Islands (UK)','--')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(263,'Virgin Islands (US)','--')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(264,'Wake Island','WQ')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(265,'Wallis and Futuna','WF')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(266,'West Bank','WE')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(267,'Western Sahara','WI')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(268,'Western Samoa','--')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(269,'World','--')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(270,'Yemen','YM')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(271,'Yugoslavia','YI')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(272,'Zaire','--')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(273,'Zambia','ZA')
insert into TempCountry(CountryId,CountryName,CountryCode)VALUES(274,'Zimbabwe','ZI')