INSERT INTO TR_SurveyAnswers(QuestionId,Answer,AnswerText)
VALUES (1,'Excellent','This is what we want')
INSERT INTO TR_SurveyAnswers(QuestionId,Answer,AnswerText)
VALUES (1,'Better','OK')
INSERT INTO TR_SurveyAnswers(QuestionId,Answer,AnswerText)
VALUES (1,'Good','Quite OK')
INSERT INTO TR_SurveyAnswers(QuestionId,Answer,AnswerText)
VALUES (1,'Outstanding','Like it very much')
INSERT INTO TR_SurveyAnswers(QuestionId,Answer,AnswerText)
VALUES (1,'Very Good','Impressive')
INSERT INTO TR_SurveyAnswers(QuestionId,Answer,AnswerText)
VALUES (1,'Worst','Not Interest')
INSERT INTO TR_SurveyAnswers(QuestionId,Answer,AnswerText)
VALUES (1,'BAD','BAD')
INSERT INTO TR_SurveyAnswers(QuestionId,Answer,AnswerText)
VALUES (1,'NOT SO SO','NOT SO SO')
INSERT INTO TR_SurveyAnswers(QuestionId,Answer,AnswerText)
VALUES (1,'OK','NOT satisfied')
INSERT INTO TR_SurveyAnswers(QuestionId,Answer,AnswerText)
VALUES (1,'TOO BAD','TOO BAD')
INSERT INTO TR_SurveyAnswers(QuestionId,Answer,AnswerText)
VALUES (1,'TOO GOOD','TOO GOOD')
INSERT INTO TR_SurveyAnswers(QuestionId,Answer,AnswerText)
VALUES (1,'VERY BAD','VERY BAD')