BEGIN TRAN
SELECT * INTO MS_RoleAccess_bACKUP_20121108 FROM MS_RoleAccess
SELECT * INTO MS_UserAccess_bACKUP_20121108 FROM MS_UserAccess

TRUNCATE TABLE MS_RoleAccess
TRUNCATE TABLE MS_UserAccess

SET IDENTITY_INSERT MS_UserAccess ON
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(1,'Customer','AddCustomer',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(2,'Customer','DeleteCustomer',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(3,'Customer','SearchCustomer',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(4,'Customer','UpdateCustomer',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(5,'Library','AddLibrary',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(6,'Library','AddLibraryCategory',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(7,'Library','DeleteLibrary',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(8,'Library','DeleteLibraryCategory',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(9,'Library','DeleteLibraryDetails',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(10,'Library','EditLibrary',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(11,'Library','GetLibraries',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(12,'Library','GetLibraryCategories',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(13,'Library','SaveGraphicFile',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(14,'Library','SaveLibraryDetails',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(15,'Library','SearchLibrary',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(16,'Library','UpdateLibraries',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(17,'Library','UpdateLibraryCategories',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(18,'Master','GetCompany',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(19,'Master','GetMaster',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(20,'Panel','AddMember',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(21,'Panel','AddPanel',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(22,'Panel','AddPanelCatetory',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(23,'Panel','AddPanelibrary',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(24,'Panel','DeleteMember',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(25,'Panel','DeletePanel',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(26,'Panel','GetCategory',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(27,'Panel','GetPanleLibrary',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(28,'Panel','Index',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(29,'Panel','SearchPanelList',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(30,'Panel','UpdateMember',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(31,'Panel','UpdatePanel',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(32,'Survey','MySurveys',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(33,'User','AddUser',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(34,'User','DeleteUser',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(35,'User','GetUsers',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(36,'User','SearchUsers',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(37,'User','UpdateUser',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(38,'Panel','SearchMemberList',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(39,'Music','AddPlayList',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(40,'Music','GetSongsInPlayList',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(41,'Music','SaveSongFile',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(42,'Music','SearchPlayList',NULL,1)
insert into MS_UserAccess(AccessId,AccessName,AccessModule,AccessLink,IsActive) values(43,'Master','GetRoles',NULL,1)

SET IDENTITY_INSERT MS_UserAccess OFF

UPDATE MS_UserAccess SET AccessLink = ''

insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',1,'AddCustomer')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',2,'DeleteCustomer')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',3,'SearchCustomer')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',4,'UpdateCustomer')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',5,'AddLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',6,'AddLibraryCategory')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',7,'DeleteLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',8,'DeleteLibraryCategory')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',9,'DeleteLibraryDetails')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',10,'EditLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',11,'GetLibraries')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',12,'GetLibraryCategories')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',13,'SaveGraphicFile')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',14,'SaveLibraryDetails')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',15,'SearchLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',16,'UpdateLibraries')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',17,'UpdateLibraryCategories')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',18,'GetCompany')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',19,'GetMaster')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',20,'AddMember')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',21,'AddPanel')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',22,'AddPanelCatetory')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',23,'AddPanelibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',24,'DeleteMember')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',25,'DeletePanel')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',26,'GetCategory')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',27,'GetPanleLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',28,'Index')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',29,'SearchPanelList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',30,'UpdateMember')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',31,'UpdatePanel')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',32,'MySurveys')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',33,'AddUser')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',34,'DeleteUser')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',35,'GetUsers')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',36,'SearchUsers')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',37,'UpdateUser')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',5,'AddLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',6,'AddLibraryCategory')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',7,'DeleteLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',8,'DeleteLibraryCategory')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',9,'DeleteLibraryDetails')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',10,'EditLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',11,'GetLibraries')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',12,'GetLibraryCategories')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',13,'SaveGraphicFile')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',14,'SaveLibraryDetails')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',15,'SearchLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',16,'UpdateLibraries')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',17,'UpdateLibraryCategories')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',19,'GetMaster')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',20,'AddMember')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',21,'AddPanel')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',22,'AddPanelCatetory')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',23,'AddPanelibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',24,'DeleteMember')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',25,'DeletePanel')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',26,'GetCategory')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',27,'GetPanleLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',28,'Index')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',29,'SearchPanelList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',30,'UpdateMember')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',31,'UpdatePanel')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',32,'MySurveys')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',33,'AddUser')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',34,'DeleteUser')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',35,'GetUsers')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',36,'SearchUsers')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',37,'UpdateUser')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',5,'AddLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',6,'AddLibraryCategory')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',7,'DeleteLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',8,'DeleteLibraryCategory')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',9,'DeleteLibraryDetails')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',10,'EditLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',11,'GetLibraries')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',12,'GetLibraryCategories')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',13,'SaveGraphicFile')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',14,'SaveLibraryDetails')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',15,'SearchLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',16,'UpdateLibraries')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',17,'UpdateLibraryCategories')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',27,'GetPanleLibrary')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',29,'SearchPanelList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',32,'MySurveys')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',38,'SearchMemberList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',38,'SearchMemberList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',39,'AddPlayList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',40,'GetSongsInPlayList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',41,'SaveSongFile')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',42,'SearchPlayList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',39,'AddPlayList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',40,'GetSongsInPlayList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',41,'SaveSongFile')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',42,'SearchPlayList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(3,'SLU',39,'AddPlayList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(3,'SLU',40,'GetSongsInPlayList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(3,'SLU',41,'SaveSongFile')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(3,'SLU',42,'SearchPlayList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',39,'AddPlayList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',40,'GetSongsInPlayList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',41,'SaveSongFile')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',42,'SearchPlayList')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',18,'GetCompany')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(2,'SA',43,'GetRoles')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(4,'SU',26,'GetCategory')
insert into MS_RoleAccess (RoleId,RoleType,AccessId,AccessModule) values(1,'GU',43,'GetRoles')

COMMIT TRAN