ALTER TABLE DBO.MS_PanelMembers DROP COLUMN Category
GO
ALTER TABLE DBO.MS_PanelMembers ADD LibId INT
GO
ALTER TABLE DBO.MS_PanelMembers ADD CONSTRAINT FK_MS_PanelMembers_TR_Library FOREIGN KEY (LibId) REFERENCES DBO.TR_Library(LibId)

