ALTER TABLE TR_InviteDetails ALTER COLUMN InviteSubject NVARCHAR(100) 
ALTER TABLE TR_InviteDetails ALTER COLUMN CustomMessage NVARCHAR(MAX) 
ALTER TABLE TR_InviteDetails ALTER COLUMN CustomReminderMessage NVARCHAR(MAX)

ALTER TABLE TR_InviteChannelDetail ALTER COLUMN InviteTitle  NVARCHAR(100)
ALTER TABLE TR_InviteChannelDetail ALTER COLUMN InviteDescription NVARCHAR(MAX)

ALTER TABLE TR_InviteLog ALTER COLUMN InviteSubject NVARCHAR(100)
ALTER TABLE TR_InviteLog ALTER COLUMN InviteMessage NVARCHAR(MAX) 
ALTER TABLE TR_InviteLog ALTER COLUMN ErrorMessage NVARCHAR(500)

ALTER TABLE TR_SurveySettings ALTER COLUMN Value NVARCHAR(1000)
ALTER TABLE PB_TR_SurveySettings ALTER COLUMN Value NVARCHAR(1000)
