ALTER TABLE DBO.TR_Survey ALTER COLUMN SurveyName NVARCHAR(50)
GO
ALTER TABLE DBO.TR_SurveyQuestions ALTER COLUMN QuestionText NVARCHAR(2000)
GO
ALTER TABLE DBO.TR_SurveyAnswers ALTER COLUMN Answer NVARCHAR(1000)
GO
ALTER TABLE DBO.TR_SurveyAnswers ALTER COLUMN AnswerText NVARCHAR(1000)

GO
ALTER TABLE DBO.PB_TR_Survey ALTER COLUMN SurveyName NVARCHAR(50)
GO
ALTER TABLE DBO.PB_TR_SurveyQuestions ALTER COLUMN QuestionText NVARCHAR(2000)
GO
ALTER TABLE DBO.PB_TR_SurveyAnswers ALTER COLUMN Answer NVARCHAR(1000)
GO
ALTER TABLE DBO.PB_TR_SurveyAnswers ALTER COLUMN AnswerText NVARCHAR(1000)