ALTER TABLE DBO.MS_Respondent ADD FirstName VARCHAR(50), LastName VARCHAR(50), BirthDate DATE, Gender CHAR(2), Town VARCHAR(50), UDF1 VARCHAR(50), UDF2 VARCHAR(50), UDF3 VARCHAR(50), UDF4 VARCHAR(50), UDF5 VARCHAR(50)
GO
ALTER TABLE DBO.MS_Respondent DROP COLUMN RespondentName
